server:
  uvicorn:
    host: 0.0.0.0
    port: 8080

chunkers:
  recursive:
    chunk-size: !ENV ${RECURSIVE_CHUNKER_CHUNK_SIZE:1100}
    chunk-overlap: !ENV ${RECURSIVE_CHUNKER_CHUNK_OVERLAP:200}
    separators: !ENV ${RECURSIVE_CHUNKER_SEPARATORS:[".", "\n\n", "\n", "--", ".", ""]}
    keep-separator: !ENV ${RECURSIVE_CHUNKER_KEEP_SEPARATOR:true}