version: 1

formatters:
  default:
    format: '%(asctime)s [%(levelname)s] [%(threadName)s] [%(module)s] [%(filename)s] - %(message)s'
    use_colors: true

filters:
  healthcheck:
    (): app.utils.healthcheck_filter.HealthcheckFilter

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    level: !ENV ${ROOT_LOG_LEVEL:DEBUG}
    stream: ext://sys.stdout
  file:
    class: app.utils.custom_rotating_file_handler.CustomRotatingFileHandler
    formatter: default
    filename: logs/server.log
    maxBytes: 1048576
    encoding: utf-8
    backupCount: 3
    level: !ENV ${ROOT_LOG_LEVEL:TRACE}
    filters:
      - healthcheck

root:
  level: !ENV ${ROOT_LOG_LEVEL:TRACE}
  handlers:
    - console
    - file

disable_existing_loggers: False